/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visualeditors.mapeditor;

import core.Config;
import core.gameobject.BaseObject;
import core.map.Map;
import java.awt.Graphics;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import visualeditors.ClassFileFilter;
import visualeditors.PanelWithThings;

/**
 *
 * @author panca
 */
public class DialogAddObject extends javax.swing.JDialog {

    private PanelWithThings panel;
    private BaseObject baseObject;
    private JPanel panelPreview;
    private JScrollPane container;
    private Map map;
    /**
     * Creates new form DialogAddObject
     */
    public DialogAddObject(java.awt.Frame parent, boolean modal, PanelWithThings panel, JScrollPane container, Map map) {
        super(parent, modal);
        this.map = map;
        this.panel = panel;
        this.container = container;
        panelPreview = new JPanel(){
            
            @Override
            public void paint(Graphics g)
            {
                if(baseObject != null)
                {
                    g.drawImage(baseObject.getCurrentSprite().getImage(), 0, 0, null);
                }
            }
            
        };
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane(panelPreview);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Preview");

        jLabel9.setText("Object Name:");

        jLabel5.setText("ClassName:");

        jButton1.setText("search...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(jLabel5))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        if(baseObject == null)
        {
            JOptionPane.showMessageDialog(this, "Create an object first!");
            return;
        }
        
        if(jTextField1.getText().length()<= 0)
        {
            this.baseObject.setName(baseObject.toString());
            jTextField1.setText(baseObject.getName());
        }
        else
            baseObject.setName(jTextField1.getText());
       
        
        if(map.getObjectByName(baseObject.getName())!=null)
        {
            JOptionPane.showMessageDialog(this, "Object called "+baseObject.getName()+" already exits. Give it another name!");
            return;
        }
            
        
        
            panel.addThing(baseObject.getCurrentSprite().getImage(), 
                    container.getViewport().getViewPosition().x+5, 
                    container.getViewport().getViewPosition().y+5, 
                    true, baseObject);
            this.dispose();

        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String choosenFile = "";
        
        JFileChooser fileChooser = new JFileChooser(Config.class.getResource("../").getPath());
        fileChooser.setFileFilter(new ClassFileFilter());
        int r = fileChooser.showOpenDialog(this);
        if (r!= JFileChooser.APPROVE_OPTION)
        return;
        choosenFile = fileChooser.getSelectedFile().getAbsolutePath();
        choosenFile = choosenFile.substring(choosenFile.indexOf(Config.PROJECT_PACKAGE));
        
        choosenFile = choosenFile.replace(File.separator+"", ".");
        choosenFile = choosenFile.substring(0,choosenFile.indexOf(".class"));
   

        try
        {
            baseObject = (BaseObject) Class.forName(choosenFile).newInstance();
           // baseObject.update(0.001);        
                    
            jTextField1.setText(baseObject.toString());

        }
        catch(ClassNotFoundException cnfe){
            cnfe.printStackTrace();
            JOptionPane.showMessageDialog(this, "Class not found!", "Class not found!", JOptionPane.ERROR_MESSAGE);
        }
        catch(InstantiationException ie){
            ie.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error Creating objetct: "+ie.getMessage(), "Error!", JOptionPane.ERROR_MESSAGE);
        }
        catch(IllegalAccessException iae){
            iae.printStackTrace();
            JOptionPane.showMessageDialog(this, "Illegal Access: "+iae.getMessage(), "Error!", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
